pipeline {
  agent any

  parameters {
    string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet to the world?')
  }

  // 각 단계를 명시
  stages {

    stage('Prepare') {
      agent any

      options {
        timeout(time: 1, unit: 'HOURS')
      }

      steps {
        echo "Download branch: ${env.BRANCH_NAME}"
        echo "${params.Greeting} World"
        echo "Clonning Repository"
        git url: 'https://github.com/frontalnh/cicd.git',
            branch: "${env.BRANCH_NAME}",
            credentialsId: 'jenkinsgit'
      }

      post {
        success {
          echo "Successfully Cloned Repository"
        }

        failure {
          echo 'Failed....'
        }

        always {
          echo 'Any way i tried'
        }

        cleanup {
          echo 'after all other post condition'
        }
      }
    }

    stage('Only in master branch') {
      when {
        expression {
          return env.BRANCH_NAME == 'master';
        }
      }

      steps {
        echo 'This is master branch'
      }
    }

    stage('some parallel stage') {
      parallel {
        stage ('parallel stage1'){
          steps {
            echo 'this is parallel stage1'
          }
        }

        stage ('parallel stage2'){
          steps {
            echo 'this is parallel stage2'
          }
        }
      }
    }
  }
}