pipeline {
  agent any

  parameters {
    string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet to the world?')
  }

  // 각 단계를 명시
  stages {
    stage('Just Test Script') {
      agent any

      steps {
        script {
          def browsers = ['chrome', 'firefox']
          for (int i=0;i<browsers.size();++i){
            echo "Testing the ${browsers[i]} browser"
          }
        }
      }
    }
  }
}